

// Copyright (c) 09-Apr-07 - 2008 Motorola, Inc. All rights reserved.


#ifndef HS_IDLE_STATUSTEXT_H
#define HS_IDLE_STATUSTEXT_H

#ifndef __cplusplus
#error "This is a C++ header file; it requires C++ to compile."
#endif

#define PHONE_IDLE_STATUS_TEXT_CHANNEL  "/phone/idle/statustext/chn"

#define PHONE_IDLE_STATUS_TEXT_MSG_KEYPADLOCK  "KEYPADLOCK"

#define PHONE_IDLE_STATUS_TEXT_MSG_SPEAKER  "SPEAKER"

#define PHONE_IDLE_STATUS_TEXT_MSG_MESSAGEFULL  "MESSAGEFULL"

#define PHONE_IDLE_STATUS_TEXT_MSG_CELLMESSAGEFULL  "CELLMESSAGEFULL"

#define PHONE_IDLE_STATUS_TEXT_MSG_POWEROFFDELAY  "POWEROFFDELAY"

#define PHONE_IDLE_STATUS_TEXT_MSG_SYNCHRONIZING  "SYNCHRONIZING"

#define PHONE_IDLE_STATUS_TEXT_MSG_CELLSMSMESSAGE  "CELLSMSMESSAGE"

#define PHONE_IDLE_STATUS_TEXT_MSG_BLUETOOTH  "BLUETOOTH"

#define PHONE_IDLE_STATUS_TEXT_MSG_SIMIDLETEXT  "SIMIDLETEXT"

#define PHONE_IDLE_STATUS_TEXT_MSG_CALLFORWARD  "CALLFORWARD"

#define PHONE_IDLE_STATUS_TEXT_MSG_CREDITAVAILABLE  "CREDITAVAILABLE"

#define PHONE_IDLE_STATUS_TEXT_MSG_CALLBARRING  "CALLBARRING"

#define PHONE_IDLE_STATUS_TEXT_MSG_AUTOANSWERON  "AUTOANSWERON"

#define PHONE_IDLE_STATUS_TEXT_MSG_GPRSACTIVE  "GPRSACTIVE"

#define PHONE_IDLE_STATUS_TEXT_MSG_SPN  "SPN"

#define PHONE_IDLE_STATUS_TEXT_MSG_GPRSATTACH  "GPRSATTACH"

#define PHONE_IDLE_STATUS_TEXT_MSG_CHARGING  "CHARGING"

#define PHONE_IDLE_STATUS_TEXT_MSG_CHARGECOMPLETED  "CHARGECOMPLETED"

#define PHONE_IDLE_STATUS_TEXT_MSG_UNABLETOCHARGE  "UNABLETOCHARGE"

#define PHONE_IDLE_STATUS_TEXT_MSG_ALERTSILENT  "ALERTSILENT"

#define PHONE_IDLE_STATUS_TEXT_MSG_DATE  "DATE"

#define FL_HS_ENGINE_TO_DATA_MODEL_CHANNEL  "Faultline_Homescreen_Engine_to_Data_Model_Channel"
#define FL_LOGO_MSG "FL_LOGO_MESSAGE"
#define FL_STATUS_TEXT_LINE_ONE_MSG "FL_STATUS_TEXT_LINE_ONE_MESSAGE"
#define FL_STATUS_TEXT_LINE_TWO_MSG "FL_STATUS_TEXT_LINE_TWO_MESSAGE"
#define FL_STK_ICON_MSG "FL_STK_ICON_MESSAGE"
#define FL_VIEW_NOTIFICATIONS_MSG "FL_VIEW_NOTIFICATIONS_MESSAGE"

#define FL_HS_DATA_MODEL_TO_ENGINE_CHANNEL "Faultline_Homescreen_Data_Model_to_Engine_Channel"
#define FL_QUERY_STATUS_TEXT_MSG "FL_QUERY_STATUS_TEXT_MESSAGE"
#define FL_SHOW_UNS_DLG "FL_SHOW_UNS_DIALOG"
#define FL_FOCUS_IN "FL_IDLE_FOCUS_IN"
#define FL_SHOW_SIDEKEY_LOCK_DLG "FL_SHOW_SIDEKEY_LOCK_DIALOG"
#define FL_SHOW_SIDEKEY_UNLOCK_DLG "FL_SHOW_SIDEKEY_UNLOCK_DIALOG"
#define FL_SHOW_CALL_DIAL_SCREEN_MSG "CallDialScreen"
#define FL_SHOW_AIRPLANEMODE_DLG "FL_SHOW_AIRPLANEMODE_DIALOG"
#define FL_SHOW_AlERT_PROMOTE_DLG "FL_SHOW_AlERT_PROMOTE_DIALOG"
#define FL_SHOW_PROFILE_PROMOTE_DLG "FL_SHOW_PROFILE_PROMOTE_DIALOG"
#define FL_SHOW_PROFILE_ERROR_DLG "FL_SHOW_PROFILE_ERROR_DIALOG"

#endif 
