

// Copyright (c) 14-Feb-08 - 2008 Motorola, Inc. All rights reserved.


#ifndef IMPSRESULTCODES_H_
#define IMPSRESULTCODES_H_

#include <global_resultcode.h>

typedef ResultCodeType PP_RETURN_STATUS_TYPE;

#define IMPS_RESULT_CODE_SUCCESS(CODE)             ((RES_SEVERITY_SUCCESS << 31) | (RES_COMP_IM << 16) | CODE)
#define IMPS_RESULT_CODE_FAILURE(CODE)             ((RES_SEVERITY_ERROR   << 31) | (RES_COMP_IM << 16) | CODE)

#define IMPS_IM_START_RANGE                        0x0000
#define IMPS_PP_START_RANGE                        0x1000

#define IMPS_RESULT_CODE_IM_SUCCESS(CODE)          IMPS_RESULT_CODE_SUCCESS(IMPS_IM_START_RANGE | CODE)
#define IMPS_RESULT_CODE_IM_FAILURE(CODE)          IMPS_RESULT_CODE_FAILURE(IMPS_IM_START_RANGE | CODE)

#define IMPS_RESULT_CODE_PP_SUCCESS(CODE)          IMPS_RESULT_CODE_SUCCESS(IMPS_PP_START_RANGE | CODE)
#define IMPS_RESULT_CODE_PP_FAILURE(CODE)          IMPS_RESULT_CODE_FAILURE(IMPS_PP_START_RANGE | CODE)

#define PP_STATUS_SUCCESS                          OPERATION_SUCCESS 
#define PP_STATUS_SUCCESS_ALREADY_INIT             IMPS_RESULT_CODE_PP_SUCCESS(0x1)

#define PP_STATUS_FAIL_NOT_INIT                    IMPS_RESULT_CODE_PP_FAILURE(0x0)
#define PP_STATUS_FAIL_INVALID_ADDRESS             IMPS_RESULT_CODE_PP_FAILURE(0x1)
#define PP_STATUS_FAIL_SESSION_NOT_AVAILABLE       IMPS_RESULT_CODE_PP_FAILURE(0x2)
#define PP_STATUS_FAIL_GENERIC                     IMPS_RESULT_CODE_PP_FAILURE(0x3)

#endif 
