

// Copyright (c) 12-Mar-07 - 2008 Motorola, Inc. All rights reserved.


#ifndef MMRESULT_H
#define MMRESULT_H

#ifndef __cplusplus
#error "This is a C++ header file; it requires C++ to compile."
#endif

enum
{
    MMRESULT_SUCCESS             = 0x00000000,

    MMRESULT_COMMON_ERROR_BASE   = 0x80000000,

    MMRESULT_UNKNOWN,

    MMRESULT_FAIL = MMRESULT_UNKNOWN, 

    MMRESULT_INVALID_INPUT,

    MMRESULT_UNSUPPORTED_OPERATION,

    MMRESULT_UNSUPPORTED_CONTROL,

    MMRESULT_ILLEGAL_STATE,

    MMRESULT_FILE_NOT_EXIST,

    MMRESULT_FILE_OPERATION_FAIL,

    MMRESULT_OUT_OF_MEMORY,

    MMRESULT_OUT_OF_SPACE,

    MMRESULT_SERVICE_BUSY,

    MMRESULT_PLAYBACK_ERROR_BASE = MMRESULT_COMMON_ERROR_BASE + 100,

    MMRESULT_CONTENT_NOT_FOUND,

    MMRESULT_INVALID_CONTENT,

    MMRESULT_UNSUPPORTED_CONTENT,

    MMRESULT_OVER_CAPABILITY,

    MMRESULT_WMDRM_INVALID_RIGHTS,

    MMRESULT_OMADRM_INVALID_RIGHTS,

    MMRESULT_WMDRM_OUTPUT_FAIL,

    MMRESULT_WMDRM_GENERAL_ERROR,

    MMRESULT_WMDRM_CLK_NOT_SET,

    MMRESULT_WMDRM_ROLLBACK,

    MMRESULT_WMDRM_HDS_FILE_CORRUPTED,

    MMRESULT_WMDRM_HDS_STORE_FULL,

    MMRESULT_WMDRM_BUFFER_TOO_SMALL,

    MMRESULT_OMADRM_OUTPUT_FAIL,

    MMRESULT_DATA_LINK_FAILED,

    MMRESULT_CONNECTION_FAIL,

    MMRESULT_CONNECTION_TIMEOUT,

    MMRESULT_AUDIO_DEVICE_FAIL,

    MMRESULT_VIDEO_DEVICE_FAIL,

    MMRESULT_FORCE_CLOSE,

    MMRESULT_CAPTURE_ERROR_BASE = MMRESULT_COMMON_ERROR_BASE + 200,

    MMRESULT_MICROPHONE_FAIL,

    MMRESULT_CAMERA_FAIL,

    MMRESULT_CAPTURE_FAIL,

    MMRESULT_ERROR_BASE=MMRESULT_COMMON_ERROR_BASE, 
    MMRESULT_ERROR_COMMON=MMRESULT_COMMON_ERROR_BASE, 
    MMRESULT_UNSUPPORTED_FORMAT=MMRESULT_UNSUPPORTED_CONTENT, 
    MMRESULT_UNIMPLEMENTED=MMRESULT_UNSUPPORTED_OPERATION, 
    MMRESULT_CREATE_FAILED=MMRESULT_FAIL, 
    MMRESULT_NO_DATA_ATTACHED=MMRESULT_UNSUPPORTED_OPERATION, 
    MMRESULT_NO_PERMISSION=MMRESULT_UNSUPPORTED_OPERATION,  
    MMRESLUT_UNSUPPORTED_PARA=MMRESULT_INVALID_INPUT, 
    MMRESULT_SYSTEM_BUSY=MMRESULT_SERVICE_BUSY, 
    MMRESULT_SYSTEM_ERR=MMRESULT_FAIL, 
    MMRESULT_MEMORY_FULL=MMRESULT_OUT_OF_MEMORY,  
    MMRESULT_FILE_OPERATION_ERR=MMRESULT_FILE_OPERATION_FAIL, 
    MMRESULT_EOF=MMRESULT_FILE_OPERATION_FAIL,   
    MMRESULT_FILE_OPEN_ERR=MMRESULT_FILE_OPERATION_FAIL, 
    MMRESULT_EXCEED_SIZE_LIMITATION=MMRESULT_OVER_CAPABILITY, 
    MMRESULT_DATA_LOST=MMRESULT_CONTENT_NOT_FOUND, 
    MMRESULT_AUTH_EXPIRED=MMRESULT_UNSUPPORTED_OPERATION, 
    MMRESULT_NET_TIMEOUT=MMRESULT_SERVICE_BUSY, 
    MMRESULT_NET_CONN_FAIL=MMRESULT_SERVICE_BUSY, 
    MMRESULT_AUDIO_DEV_OPEN_FAILED=MMRESULT_AUDIO_DEVICE_FAIL, 
    MMRESULT_MICPHONE_DEV_FAILED=MMRESULT_AUDIO_DEVICE_FAIL, 
    MMRESULT_PHONE_INPUT_FAILED=MMRESULT_AUDIO_DEVICE_FAIL, 
    MMRESULT_PLUGIN_NOT_FOUND=MMRESULT_UNSUPPORTED_OPERATION, 
    MMRESULT_PLUGIN_INVALID=MMRESULT_UNSUPPORTED_OPERATION, 
    MMRESULT_TRY_LATER=MMRESULT_SERVICE_BUSY, 
    MMRESULT_ENCODING_FAILED=MMRESULT_UNSUPPORTED_CONTENT, 
    MMRESULT_NO_SPACE=MMRESULT_OUT_OF_SPACE, 
    MMRESULT_MAXIMUM_LISTENERS_REACHED=MMRESULT_OVER_CAPABILITY, 
    MMRESULT_CAPABILITY_CHECK_FAILED=MMRESULT_OVER_CAPABILITY, 
    MMRESULT_NAPI_INIT_FAILED=MMRESULT_DATA_LINK_FAILED,  
    MMRESULT_NAPI_OPEN_FAILED=MMRESULT_DATA_LINK_FAILED, 
    MMRESULT_NAPI_MSG_FAILED=MMRESULT_DATA_LINK_FAILED, 
    MMRESULT_NAPI_FAILED=MMRESULT_DATA_LINK_FAILED,     
    MMRESULT_SEEK_ON_GOING=MMRESULT_SERVICE_BUSY,     
    MMRESULT_INVALID_RIGHTS=MMRESULT_WMDRM_INVALID_RIGHTS, 
    MMRESULT_EDITOR_BASE=MMRESULT_COMMON_ERROR_BASE,    
    MMRESULT_EDITOR_CANNOTOVERLAYMULTIIMAGE=MMRESULT_FAIL, 
    MMRESULT_CAM_BASE=MMRESULT_CAPTURE_ERROR_BASE,       
    MMRESULT_CAM_NONE=MMRESULT_FAIL,       
    MMRESULT_CAM_DEV_OPEN_FAIL=MMRESULT_VIDEO_DEVICE_FAIL, 
    MMRESULT_CAM_DEV_IOC_FAIL=MMRESULT_VIDEO_DEVICE_FAIL, 
    MMRESULT_CAM_DEV_ERROR=MMRESULT_VIDEO_DEVICE_FAIL, 
    MMRESULT_CAM_DEV_INVALID=MMRESULT_VIDEO_DEVICE_FAIL, 
    MMRESULT_CAM_DEV_TIMEOUT=MMRESULT_VIDEO_DEVICE_FAIL, 
    MMRESULT_CAM_DEV_NOTSUP=MMRESULT_VIDEO_DEVICE_FAIL, 
    MMRESULT_CAM_DEV_NOMEM=MMRESULT_OUT_OF_MEMORY, 
    MMRESULT_CAM_CAPTURE_FAILED=MMRESULT_CAPTURE_FAIL, 
    MMRESULT_CAM_SAVE_FAILED=MMRESULT_FILE_OPERATION_FAIL, 
    MMRESULT_CAM_INVALID_FORMAT=MMRESULT_UNSUPPORTED_OPERATION 

};

typedef int MMResult;

#define MMRESULT_MAP_NAME(errCode) ( \
    (errCode == (int)MMRESULT_SUCCESS) ? "MMRESULT_SUCCESS": \
    (errCode == (int)MMRESULT_COMMON_ERROR_BASE) ? "MMRESULT_COMMON_ERROR_BASE": \
    (errCode == (int)MMRESULT_UNKNOWN) ? "MMRESULT_UNKNOWN": \
    (errCode == (int)MMRESULT_FAIL) ? "MMRESULT_FAIL": \
    (errCode == (int)MMRESULT_INVALID_INPUT) ? "MMRESULT_INVALID_INPUT": \
    (errCode == (int)MMRESULT_UNSUPPORTED_OPERATION) ? "MMRESULT_UNSUPPORTED_OPERATION": \
    (errCode == (int)MMRESULT_UNSUPPORTED_CONTROL) ? "MMRESULT_UNSUPPORTED_CONTROL": \
    (errCode == (int)MMRESULT_ILLEGAL_STATE) ? "MMRESULT_ILLEGAL_STATE": \
    (errCode == (int)MMRESULT_FILE_OPERATION_FAIL) ? "MMRESULT_FILE_OPERATION_FAIL": \
    (errCode == (int)MMRESULT_OUT_OF_MEMORY) ? "MMRESULT_OUT_OF_MEMORY": \
    (errCode == (int)MMRESULT_OUT_OF_SPACE) ? "MMRESULT_OUT_OF_SPACE": \
    (errCode == (int)MMRESULT_SERVICE_BUSY) ? "MMRESULT_SERVICE_BUSY": \
    (errCode == (int)MMRESULT_PLAYBACK_ERROR_BASE) ? "MMRESULT_PLAYBACK_ERROR_BASE": \
    (errCode == (int)MMRESULT_CONTENT_NOT_FOUND) ? "MMRESULT_CONTENT_NOT_FOUND": \
    (errCode == (int)MMRESULT_INVALID_CONTENT) ? "MMRESULT_INVALID_CONTENT": \
    (errCode == (int)MMRESULT_UNSUPPORTED_CONTENT) ? "MMRESULT_UNSUPPORTED_CONTENT": \
    (errCode == (int)MMRESULT_OVER_CAPABILITY) ? "MMRESULT_OVER_CAPABILITY": \
    (errCode == (int)MMRESULT_WMDRM_INVALID_RIGHTS) ? "MMRESULT_WMDRM_INVALID_RIGHTS": \
    (errCode == (int)MMRESULT_OMADRM_INVALID_RIGHTS) ? "MMRESULT_OMADRM_INVALID_RIGHTS": \
    (errCode == (int)MMRESULT_WMDRM_OUTPUT_FAIL) ? "MMRESULT_WMDRM_OUTPUT_FAIL": \
    (errCode == (int)MMRESULT_WMDRM_GENERAL_ERROR) ? "MMRESULT_WMDRM_GENERAL_ERROR": \
    (errCode == (int)MMRESULT_OMADRM_OUTPUT_FAIL) ? "MMRESULT_OMADRM_OUTPUT_FAIL": \
    (errCode == (int)MMRESULT_DATA_LINK_FAILED) ? "MMRESULT_DATA_LINK_FAILED": \
    (errCode == (int)MMRESULT_CONNECTION_FAIL) ? "MMRESULT_CONNECTION_FAIL": \
    (errCode == (int)MMRESULT_CONNECTION_TIMEOUT) ? "MMRESULT_CONNECTION_TIMEOUT": \
    (errCode == (int)MMRESULT_AUDIO_DEVICE_FAIL) ? "MMRESULT_AUDIO_DEVICE_FAIL": \
    (errCode == (int)MMRESULT_VIDEO_DEVICE_FAIL) ? "MMRESULT_VIDEO_DEVICE_FAIL": \
    (errCode == (int)MMRESULT_CAPTURE_ERROR_BASE) ? "MMRESULT_CAPTURE_ERROR_BASE": \
    (errCode == (int)MMRESULT_MICROPHONE_FAIL) ? "MMRESULT_MICROPHONE_FAIL": \
    (errCode == (int)MMRESULT_CAMERA_FAIL) ? "MMRESULT_CAMERA_FAIL": \
    (errCode == (int)MMRESULT_CAPTURE_FAIL) ? "MMRESULT_CAPTURE_FAIL": \
    (errCode == (int)MMRESULT_ERROR_BASE) ? "MMRESULT_ERROR_BASE": \
    (errCode == (int)MMRESULT_ERROR_COMMON) ? "MMRESULT_ERROR_COMMON": \
    (errCode == (int)MMRESULT_UNSUPPORTED_FORMAT) ? "MMRESULT_UNSUPPORTED_FORMAT": \
    (errCode == (int)MMRESULT_UNIMPLEMENTED) ? "MMRESULT_UNIMPLEMENTED": \
    (errCode == (int)MMRESULT_CREATE_FAILED) ? "MMRESULT_CREATE_FAILED": \
    (errCode == (int)MMRESULT_NO_DATA_ATTACHED) ? "MMRESULT_NO_DATA_ATTACHED": \
    (errCode == (int)MMRESULT_NO_PERMISSION) ? "MMRESULT_NO_PERMISSION": \
    (errCode == (int)MMRESULT_SYSTEM_BUSY) ? "MMRESULT_SYSTEM_BUSY": \
    (errCode == (int)MMRESULT_SYSTEM_ERR) ? "MMRESULT_SYSTEM_ERR": \
    (errCode == (int)MMRESULT_MEMORY_FULL) ? "MMRESULT_MEMORY_FULL": \
    (errCode == (int)MMRESULT_FILE_OPERATION_ERR) ? "MMRESULT_FILE_OPERATION_ERR": \
    (errCode == (int)MMRESULT_FILE_NOT_EXIST) ? "MMRESULT_FILE_NOT_EXIST": \
    (errCode == (int)MMRESULT_EOF) ? "MMRESULT_EOF": \
    (errCode == (int)MMRESULT_FILE_OPEN_ERR) ? "MMRESULT_FILE_OPEN_ERR": \
    (errCode == (int)MMRESULT_EXCEED_SIZE_LIMITATION) ? "MMRESULT_EXCEED_SIZE_LIMITATION": \
    (errCode == (int)MMRESULT_DATA_LOST) ? "MMRESULT_DATA_LOST": \
    (errCode == (int)MMRESULT_AUTH_EXPIRED) ? "MMRESULT_AUTH_EXPIRED": \
    (errCode == (int)MMRESULT_NET_TIMEOUT) ? "MMRESULT_NET_TIMEOUT": \
    (errCode == (int)MMRESULT_NET_CONN_FAIL) ? "MMRESULT_NET_CONN_FAIL": \
    (errCode == (int)MMRESULT_AUDIO_DEV_OPEN_FAILED) ? "MMRESULT_AUDIO_DEV_OPEN_FAILED": \
    (errCode == (int)MMRESULT_MICPHONE_DEV_FAILED) ? "MMRESULT_MICPHONE_DEV_FAILED": \
    (errCode == (int)MMRESULT_PHONE_INPUT_FAILED) ? "MMRESULT_PHONE_INPUT_FAILED": \
    (errCode == (int)MMRESULT_PLUGIN_NOT_FOUND) ? "MMRESULT_PLUGIN_NOT_FOUND": \
    (errCode == (int)MMRESULT_PLUGIN_INVALID) ? "MMRESULT_PLUGIN_INVALID": \
    (errCode == (int)MMRESULT_TRY_LATER) ? "MMRESULT_TRY_LATER": \
    (errCode == (int)MMRESULT_ENCODING_FAILED) ? "MMRESULT_ENCODING_FAILED": \
    (errCode == (int)MMRESULT_NO_SPACE) ? "MMRESULT_NO_SPACE": \
    (errCode == (int)MMRESULT_MAXIMUM_LISTENERS_REACHED) ? "MMRESULT_MAXIMUM_LISTENERS_REACHED": \
    (errCode == (int)MMRESULT_CAPABILITY_CHECK_FAILED) ? "MMRESULT_CAPABILITY_CHECK_FAILED": \
    (errCode == (int)MMRESULT_NAPI_INIT_FAILED) ? "MMRESULT_NAPI_INIT_FAILED": \
    (errCode == (int)MMRESULT_NAPI_OPEN_FAILED) ? "MMRESULT_NAPI_OPEN_FAILED": \
    (errCode == (int)MMRESULT_NAPI_MSG_FAILED) ? "MMRESULT_NAPI_MSG_FAILED": \
    (errCode == (int)MMRESULT_NAPI_FAILED) ? "MMRESULT_NAPI_FAILED": \
    (errCode == (int)MMRESULT_SEEK_ON_GOING) ? "MMRESULT_SEEK_ON_GOING": \
    (errCode == (int)MMRESULT_INVALID_RIGHTS) ? "MMRESULT_INVALID_RIGHTS": \
    (errCode == (int)MMRESULT_EDITOR_BASE) ? "MMRESULT_EDITOR_BASE": \
    (errCode == (int)MMRESULT_EDITOR_CANNOTOVERLAYMULTIIMAGE) ? "MMRESULT_EDITOR_CANNOTOVERLAYMULTIIMAGE": \
    (errCode == (int)MMRESULT_CAM_BASE) ? "MMRESULT_CAM_BASE": \
    (errCode == (int)MMRESULT_CAM_NONE) ? "MMRESULT_CAM_NONE": \
    (errCode == (int)MMRESULT_CAM_DEV_OPEN_FAIL) ? "MMRESULT_CAM_DEV_OPEN_FAIL": \
    (errCode == (int)MMRESULT_CAM_DEV_IOC_FAIL) ? "MMRESULT_CAM_DEV_IOC_FAIL": \
    (errCode == (int)MMRESULT_CAM_DEV_ERROR) ? "MMRESULT_CAM_DEV_ERROR": \
    (errCode == (int)MMRESULT_CAM_DEV_INVALID) ? "MMRESULT_CAM_DEV_INVALID": \
    (errCode == (int)MMRESULT_CAM_DEV_TIMEOUT) ? "MMRESULT_CAM_DEV_TIMEOUT": \
    (errCode == (int)MMRESULT_CAM_DEV_NOTSUP) ? "MMRESULT_CAM_DEV_NOTSUP": \
    (errCode == (int)MMRESULT_CAM_DEV_NOMEM) ? "MMRESULT_CAM_DEV_NOMEM": \
    (errCode == (int)MMRESULT_CAM_CAPTURE_FAILED) ? "MMRESULT_CAM_CAPTURE_FAILED": \
    (errCode == (int)MMRESULT_CAM_SAVE_FAILED) ? "MMRESULT_CAM_SAVE_FAILED": \
    (errCode == (int)MMRESULT_CAM_INVALID_FORMAT) ? "MMRESULT_CAM_INVALID_FORMAT": \
    "Unknown" )

#endif

