

// Copyright (c) 26-Apr-07 - 2008 Motorola, Inc. All rights reserved.


#ifndef PHONE_IDLE_STATUS_TEXT_H
#define PHONE_IDLE_STATUS_TEXT_H

#define PHONE_IDLE_STATUS_TEXT_CHANNEL  "/phone/idle/statustext/chn"

#define PHONE_IDLE_STATUS_TEXT_MSG_KEYPADLOCK  "KEYPADLOCK"
#define PHONE_IDLE_STATUS_TEXT_MSG_SPEAKER  "SPEAKER"
#define PHONE_IDLE_STATUS_TEXT_MSG_MESSAGEFULL  "MESSAGEFULL"
#define PHONE_IDLE_STATUS_TEXT_MSG_CELLMESSAGEFULL  "CELLMESSAGEFULL"
#define PHONE_IDLE_STATUS_TEXT_MSG_POWEROFFDELAY  "POWEROFFDELAY"
#define PHONE_IDLE_STATUS_TEXT_MSG_SYNCHRONIZING  "SYNCHRONIZING"
#define PHONE_IDLE_STATUS_TEXT_MSG_CELLSMSMESSAGE  "CELLSMSMESSAGE"
#define PHONE_IDLE_STATUS_TEXT_MSG_BLUETOOTH  "BLUETOOTH"
#define PHONE_IDLE_STATUS_TEXT_MSG_SIMIDLETEXT  "SIMIDLETEXT"
#define PHONE_IDLE_STATUS_TEXT_MSG_CALLFORWARD  "CALLFORWARD"
#define PHONE_IDLE_STATUS_TEXT_MSG_CREDITAVAILABLE  "CREDITAVAILABLE"
#define PHONE_IDLE_STATUS_TEXT_MSG_CALLBARRING  "CALLBARRING"
#define PHONE_IDLE_STATUS_TEXT_MSG_AUTOANSWERON  "AUTOANSWERON"
#define PHONE_IDLE_STATUS_TEXT_MSG_GPRSACTIVE  "GPRSACTIVE"
#define PHONE_IDLE_STATUS_TEXT_MSG_SPN  "SPN"
#define PHONE_IDLE_STATUS_TEXT_MSG_GPRSATTACH  "GPRSATTACH"
#define PHONE_IDLE_STATUS_TEXT_MSG_CHARGING  "CHARGING"
#define PHONE_IDLE_STATUS_TEXT_MSG_CHARGECOMPLETED  "CHARGECOMPLETED"
#define PHONE_IDLE_STATUS_TEXT_MSG_UNABLETOCHARGE  "UNABLETOCHARGE"
#define PHONE_IDLE_STATUS_TEXT_MSG_ALERTSILENT  "ALERTSILENT"
#define PHONE_IDLE_STATUS_TEXT_MSG_DATE  "DATE"

#endif 
