

// Copyright (c) 26-Apr-07 - 2008 Motorola, Inc. All rights reserved.


#ifndef PHONE_COPCHANNELS_H
#define PHONE_COPCHANNELS_H

#ifndef __cplusplus
#error "This is a C++ header file; it requires C++ to compile."
#endif

#define PHONE_UACCOUNT_CHANNEL "/EZX/PHONE/USIMACCOUNT"
#define PHONE_SETUP_MSG_PUK_2_SUCC "/EZX/PHONE/SETUP/MSG/PUK/2/SUCC" 
#define POWER_USIM_ACCOUNT_LIST "ACCOUNT LIST"
#define SIMUPIN_BLOCK "SIMUPIN_Block"
#define SIMUPIN_PERMANENT_BLOCK "SIMUPIN_Permanent_Block"

#define PHONE_INCOMINGCALL_CHANNEL "/EZX/PHONE/INCOMING_CALL" 
#define PHONE_AUDIOPATH_CHANNEL "/EZX/PHONE/AUDIO_PATH"
#define PHONE_SIMSTATUS_CHANNEL "/EZX/PHONE/SIM"
#define PHONE_VOLUMN_CHANNEL "/EZX/PHONE/VOLUMN"
#define PHONE_OUTGOING_CHANNEL "/EZX/PHONE/OUTGOING_CALL"
#define PHONE_PHONELOCK_CHANNEL "/EZX/PHONE/PHONE_LOCK"
#define PHONE_GNB_CHANNEL "/EZX/PHONE/GNB_UPDATE"
#define PHONE_POWERON_INFO_CHANNEL "/EZX/PHONE/POWERON"
#define PHONE_TTY_CHANNEL "/EZX/PHONE/TTY"
#define PHONE_SETUP_CHANNEL "/EZX/PHONE/SETUP"
#define PHONE_UACCOUNT_CHANNEL "/EZX/PHONE/USIMACCOUNT"

#define PHONE_SETUP_MSG_PUK_1_SUCC "/EZX/PHONE/SETUP/MSG/PUK/1/SUCC"
#define ACESSORY_PATH_PIHF                 "PIHF"
#define ACESSORY_PATH_EIHF                 "EIHF"
#define ACESSORY_PATH_FM                   "FM"
#define ACESSORY_PATH_BTHEADSET           "BTHS"
#define ACESSORY_PATH_BTCARKIT             "BTCARKIT"
#define ACESSORY_PATH_HEADSET             "HEADSET"
#define ACESSORY_PATH_SPEAKERPHONE       "SPEAKPHONE"
#define ACESSORY_PATH_NORMALPHONE        "NORMALPHONE"
#define ACESSORY_PATH_FLIPRECEIVER        "FLIPRECEIVER"
#define SIM_CARD_STATUS_OK "SIM OK"
#define SIM_CARD_STATUS_ERROR "SIM ERROR"
#define PIN_STATUS_NORMAL "PIN OK"
#define PIN_STATUS_ERROR "PIN ERROR"
#define SIMPIN1_BLOCK "SIMPIN1_Block"
#define SIMPIN2_BLOCK "SIMPIN2_Block"
#define SIMPIN2_PERMANENT_BLOCK "SIMPIN2_Permanent_Block"
#define PHONE_SETUP_MSG_PUK_2_SUCC "/EZX/PHONE/SETUP/MSG/PUK/2/SUCC"
#define SIMUPIN_UPIN_BLOCK "UPIN_Block"
#define SIMUPIN_PERMANENT_BLOCK "SIMUPIN_Permanent_Block"
#define POWER_USIM_ACCOUNT_LIST "ACCOUNT LIST"
#define SETUP_CHANGE_SPEAKER_VOLUMN "SETUP SPEAKER VOL"
#define MO_CALL_INITIATE "MO"
#define MO_CALL_ENDED "ENDED"
#define PHONE_LOCK_STATUS_CHANGED "LOCK STATUS CHANGED"
#define PHONE_GNB_UPDATED "UPDATE GNB"
#define PHONE_SHOW_WELCOME_MESSAGE "welcomeText"
#define TTY_MSG_TTY_MODE_CHANGED "TTY MODE CHANGED"
#define IDLE_NOTICE "Idle_Notice"
#define MEDIA_PLAYER "Media_player"
#define FDN_STATUS_CHANGED "fdn_status_changed"
#define PHONE_SECURITY_NOTICE "Phone_Security_Notice"
#define PHONE_SECURITY_FRAME_NOTICE "/ezx/phone/phone_security_frame_notice"
#define PHONE_IS_LOCK "Phone_Lock"
#define PHONE_SETUP_CALLFORWARD_NOTICE "Call_Forward_Notice"
#define PHONE_SETUP_CALLFORWARD_STATE_CHANGE "Call_Forward_State_Change"
#define IDLE_SIDEKEY_NOTICE "Idle_Sidekey_Notice"
#define IDLE_SIDEKEY_STATE_CHANGE "Idle_Sidekey_State_Change"
#define PHONE_MESSAGE_VOICEMAIL_STATUS "Messsage_VoiceMail_Status"
#define VOICE_MAIL_CHANGED "Voice_Mail_Changed"

#endif

