

// Copyright (c) 15-Jan-03 - 2008 Motorola, Inc. All rights reserved.


#ifndef QT_NO_QWS_MMI_TEST
#ifndef __QPACKDEF_H__
#define __QPACKDEF_H__

#define ITEM_RECT_OFFSET 16
#define ITEM_TYPE_OFFSET 24
#define ITEM_STATE_OFFSET 25
#define ITEM_SUBTYPE_OFFSET 26
#define TEXT_POINTER_OFFSET 27
#define ICON_POINTER_OFFSET 28
enum {
    	ACTION_TYPE=1,
    	BUTTON_TYPE=2,
    	BUTTONGROUP_TYPE=3,
    	CDESTYLE_TYPE=4,
    	CHECKBOX_TYPE=5,
    	COMBOBOX_TYPE=6,
    	COMMONSTYLE_TYPE=7,
    	COMPACTSTYLE_TYPE=8,
    	DIAL_TYPE=9,
    	EFFECTS_TYPE=10,
    	FRAME_TYPE=11,
    	GRID_TYPE=12,
    	GROUPBOX_TYPE=13,
    	HBOX_TYPE=14,
    	HBUTTONGROUP_TYPE=15,
    	HEADER_TYPE=16,
    	HEADERSECT_TYPE=17,
    	HGROUPBOX_TYPE=18,
       ICONVIEW_TYPE=19,
       ICONVIEWITEM_TYPE=20,
    	INTERLACESTYLE_TYPE=21,
    	LABEL_TYPE=22,
    	LCDNUMBER_TYPE=23,
    	LINEEDIT_TYPE=24,
    	LISTBOX_TYPE=25,
       LISTBOXITEM_TYPE=26,
    	LISTVIEW_TYPE=27,
    	MAINWINDOW_TYPE=28,
    	MENUBAR_TYPE=29,
    	MENUDATA_TYPE=30,
    	MOTIFPLUSSTYLE_TYPE=31,
    	MOTIFSTYLE_TYPE=32,
    	MULTILINEEDIT_TYPE=33,
       MULTILINEROW_TYPE=34,
    	PLATINUMSTYLE_TYPE=35,
    	POPUPMENU_TYPE=36,
       POPUPMENUITEM_TYPE=37,
    	PROGRESSBAR_TYPE=38,
    	PUSHBUTTON_TYPE=39,
    	RADIOBUTTON_TYPE=40,
    	RANGECONTROL_TYPE=41,
    	SCROLLBAR_TYPE=42,
    	SCROLLVIEW_TYPE=43,
    	SGISTYLE_TYPE=44,
    	SLIDER_TYPE=45,
    	SPINBOX_TYPE=46,
    	SPLITTER_TYPE=47,
    	STATUSBAR_TYPE=48,
    	TABBAR_TYPE=49,
       TABLE_TYPE=50,
       TABLEITEM_TYPE=51,
    	TABLEVIEW_TYPE=52,
    	TABWIDGET_TYPE=53,
    	TEXTBROWSER_TYPE=54,
    	TEXTVIEW_TYPE=55,
    	TOOLBAR_TYPE=56,
    	TOOLBUTTON_TYPE=57,
    	TOOLTIP_TYPE=58,
    	VALIDATOR_TYPE=59,
    	VBOX_TYPE=60,
    	VBUTTONGROUP_TYPE=61,
    	WHATSTHIS_TYPE=62,
    	WIDGET_TYPE=63,
    	WIDGETSTACK_TYPE=64,
    	WINDOWSTYLE_TYPE=65,

    	LISTVIEWITEM_TYPE=66,
    	PIXMAP_TYPE=67,
    	TIMER_TYPE=68,
    	DESKTOPBG_TYPE=69,
    	TAB_TYPE=70,
    	DIALOG_TYPE=71,
    	TEXT_TYPE=72,
    	RECTANGLE_TYPE=73,

    	UTIL_CHECKLISTITEM_TYPE=80,
    	UTIL_DIALOG_TYPE=81,
    	UTIL_DLGCST_TYPE=82,
    	UTIL_LISTBOX_TYPE=83,
    	UTIL_LISTBOXDLG_TYPE=84,
    	UTIL_LISTBOXITEM_TYPE=85,
    	UTIL_LISTVIEWITEM_TYPE=86,
    	UTIL_MAINWIDGET_TYPE=87,
    	UTIL_MESSAGEBOX_TYPE=88,
    	UTIL_MULTILINEEDIT_TYPE=89,
    	UTIL_PROGRESSDIALOG_TYPE=90,
    	UTIL_SCROLLVIEW_TYPE=91,

	UTIL_ANALOGCLOCK_TYPE=92,
	UTIL_DATEPICKER_TYPE=93,
	UTIL_TIMERPICKER_TYPE=94,
	UTIL_BASEDIALOG_TYPE=95,
	UTIL_DATEPICKERDIALOG_TYPE=96,
	UTIL_TIMEPICKERDIALOG_TYPE=97,
	UTIL_SPINBUTTON_TYPE=98,
	AM_NORMALGNB_TYPE=99,
	AM_NOTIFYGNB_TYPE=100,
	AM_STATUS_MAINWINDOW_TYPE=101,
	SIZEGRIP_TYPE=102,

	USER_DEFINED_TYPE=200
};
#endif
#endif 
