

// Copyright (c) 22-Nov-06 - 2008 Motorola, Inc. All rights reserved.


#ifndef _TAPI_APPMSGID_H 
#define _TAPI_APPMSGID_H

#ifdef __cplusplus 
extern "C" {
#endif

#include "EZX_TypeDefs.h"

    enum TAPI_APP_ASYNC_GROUP_ID_E
    {

        TAPI_APP_INVALID_MSGID              = 0,    

        TAPI_APP_ASYNC_MIN_MSG_GRPID        = 0x0100,   
        TAPI_APP_ASYNC_FRM_MSG_GRPID        = TAPI_APP_ASYNC_MIN_MSG_GRPID,
        TAPI_APP_ASYNC_VOICECALL_MSG_GRPID  = 0x0200,   
        TAPI_APP_ASYNC_MSG_MSG_GRPID        = 0x0300,   
        TAPI_APP_ASYNC_SIM_MSG_GRPID        = 0x0400,   
        TAPI_APP_ASYNC_SECURITY_MSG_GRPID   = 0x0500,   
        TAPI_APP_ASYNC_ACCEORY_MSG_GRPID    = 0x0600,   
        TAPI_APP_ASYNC_NETWORK_MSG_GRPID    = 0x0700,   
        TAPI_APP_ASYNC_GPRS_MSG_GRPID       = 0x0800,   
        TAPI_APP_ASYNC_STK_MSG_GRPID        = 0x0900,   
        TAPI_APP_ASYNC_CSD_MSG_GRPID        = 0x0A00,   
        TAPI_APP_ASYNC_CALLSET_MSG_GRPID    = 0x0B00,   
        TAPI_APP_ASYNC_CB_MSG_GRPID         = 0x0C00,   
        TAPI_APP_ASYNC_USSD_MSG_GRPID       = 0x0D00,   
        TAPI_APP_ASYNC_FAX_MSG_GRPID        = 0x0E00,   
        TAPI_APP_ASYNC_EFEM_MSG_GRPID       = 0x0F00,   
        TAPI_APP_ASYNC_FTA_MSG_GRPID        = 0x1000,   
        TAPI_APP_ASYNC_MISC_MSG_GRPID       = 0x1100,   
        TAPI_APP_ASYNC_SYNC_MSG_GRPID       = 0x1200,   
        TAPI_APP_ASYNC_UMAN_MSG_GRPID       = 0x1300,   
        TAPI_APP_ASYNC_LOG_MSG_GRPID        = 0x1400,   
        TAPI_APP_ASYNC_APR_MSG_GRPID        = 0x1500,   
        TAPI_APP_ASYNC_CALL_MSG_GRPID       = 0x1600,   
        TAPI_APP_ASYNC_KODIAK_MSG_GRPID     = 0x1700,   
        TAPI_APP_ASYNC_STK_MULTI_REG_MSG_GRPID = 0x1800,   
        TAPI_APP_ASYNC_MAX_MSG_GRPID        = TAPI_APP_ASYNC_STK_MULTI_REG_MSG_GRPID + 0x0100  
    };

enum _TAPI_APP_MSGID_T
{

    TAPI_VOICE_NOTIFY_STATUS_MSGID               = TAPI_APP_ASYNC_VOICECALL_MSG_GRPID + 1,   

    TAPI_VOICE_NOTIFY_INCOMING_MSGID,            

    TAPI_VOICE_NOTIFY_SERVICE_RESULT_MSGID,      

    TAPI_VOICE_NOTIFY_USSD_MSGID,                

    TAPI_NOTIFY_PANIC_MSGID,                     

    TAPI_VOICE_NOTIFY_CURRENT_COST_MSGID,        

    TAPI_VOICE_NOTIFY_CREDIT_MODE_MSGID,         

    TAPI_VOICE_NOTIFY_INTERMEDIATE_SERVICE_MSGID,

    TAPI_VOICE_NOTIFY_CALL_CONTROL_MSGID,        

    TAPI_VOICE_NOTIFY_OTHERAPP_CALLING_MSGID,    

    TAPI_VOICE_NOTIFY_OTHERAPP_CONNECTING_MSGID, 

    TAPI_VOICE_NOTIFY_OTHERAPP_JOINING_MSGID,    

    TAPI_VOICE_NOTIFY_OTHERAPP_SPLITING_MSGID,   

    TAPI_TTY_NOTIFY_TTY_TONE_MSGID,              

    TAPI_VOICE_NOTIFY_BP_AUDIO_STATUS_MSGID,     

    TAPI_VOICE_NOTIFY_MUTE_STATUS_MSGID,         

    TAPI_NOTIFY_CALL_LINE_INFO_MSGID,            

    TAPI_VOICE_NOTIFY_TCH_AVAILABLE_MSGID,       

    TAPI_VOICE_NOTIFY_DTMF_STRING_CONFIRM_MSGID, 

    TAPI_VOICE_NOTIFY_CALL_TRANSFER_MSGID,	 

    TAPI_APP_ASYNC_VOICECALL_MSG_GRPID_END       = TAPI_VOICE_NOTIFY_CALL_TRANSFER_MSGID, 

    TAPI_SMS_SYNC_END_MSGID                      = TAPI_APP_ASYNC_MSG_MSG_GRPID + 1, 

    TAPI_SMS_NOTIFY_SIM_FULL_MSGID,              
    TAPI_SMS_NOTIFY_SIM_AVAIL_MSGID,             

    TAPI_SMS_NOTIFY_RECV_NEW_SM_MSGID,           

    TAPI_SMS_NOTIFY_RECV_AT_NEW_SM_MSGID,        

    TAPI_SMS_NOTIFY_RECV_STATUS_REPORT_MSGID,    

    TAPI_SMS_NOTIFY_RECV_PORTNUM_SM_MSGID,       

    TAPI_SMS_NOTIFY_RECV_VM_SM_MSGID,            

    TAPI_SMS_NOTIFY_RECV_AT_VM_SM_MSGID,         

    TAPI_SMS_NOTIFY_RECV_ORANGE_MOSES_SM_MSGID,  

    TAPI_SMS_NOTIFY_RECV_PDU_SM_MSGID,           

    TAPI_SMS_NOTIFY_SEND_CNF_MSGID,              

    TAPI_SMS_NOTIFY_MO_CONTROL_MSGID,            

    TAPI_SMS_NOTIFY_RECV_RAW_MSGID,              

    TAPI_APP_ASYNC_MSG_MSG_GRPID_END             = TAPI_SMS_NOTIFY_RECV_RAW_MSGID, 

    TAPI_SIM_NOTIFY_PHONEBOOK_READY_MSGID        = TAPI_APP_ASYNC_SIM_MSG_GRPID + 1, 

    TAPI_SIM_NOTIFY_FIXDIALING_READY_MSGID,      
    TAPI_SIM_NOTIFY_MSISDN_READY_MSGID,          
    TAPI_SIM_NOTIFY_FIXDIALING_STATUS_REFRESHED_MSGID,  

    TAPI_SIM_NOTIFY_IMSI_MSGID,                  

    TAPI_SIM_NOTIFY_CARD_STATUS_MSGID,           

    TAPI_SIM_NOTIFY_PIN1_STATUS_MSGID,           

    TAPI_SIM_NOTIFY_PIN_STATUS_MSGID,           

    TAPI_SIM_NOTIFY_BLOCK_STATUS_MSGID,          

    TAPI_SIM_NOTIFY_SUBSIDY_STATUS_MSGID,        

    TAPI_CPHS_NOTIFY_INFO_MSGID,                 

    TAPI_CPHS_NOTIFY_WAITTING_MESSAGE_MSGID,     

    TAPI_SIM_NOTIFY_REFRESH_MSGID,               

    TAPI_SIM_NOTIFY_REFRESH_END_MSGID,           

    TAPI_NOTIFY_FLEX_CHANGED_MSGID, 
    TAPI_SIM_NOTIFY_SDN_READY_MSGID,             
    TAPI_SIM_NOTIFY_PROVISION_READY_MSGID, 
    TAPI_SIM_APDU_SEND_ASYNC_CNF_MSGID,          
    TAPI_SIM_READ_FILE_CNF_MSGID,                

    TAPI_SIM_WRITE_FILE_CNF_MSGID,               

    TAPI_APP_ASYNC_SIM_MSG_GRPID_END             = TAPI_SIM_WRITE_FILE_CNF_MSGID,

    TAPI_POWER_NOTIFY_SUSPEND_MSGID              = TAPI_APP_ASYNC_ACCEORY_MSG_GRPID + 1, 
    TAPI_ACCE_NOTIFY_TIME_CHANGED_MSGID,         

    TAPI_BLUETOOTH_NOTIFY_CALL_ALERT_MSGID,      

    TAPI_APP_ASYNC_ACCEORY_MSG_GRPID_END         = TAPI_BLUETOOTH_NOTIFY_CALL_ALERT_MSGID,

    TAPI_NETWORK_NOTIFY_SIGNAL_QUALITY_MSGID     = TAPI_APP_ASYNC_NETWORK_MSG_GRPID + 1, 

    TAPI_NETWORK_NOTIFY_SERVICE_AVAILABILITY_MSGID,

    TAPI_NETWORK_NOTIFY_ROAM_STATUS_MSGID,       

    TAPI_SIM_NOTIFY_TEST_CARD_MSGID,             

    TAPI_SIM_NOTIFY_PREPAID_CARD_MSGID,          

    TAPI_NETWORK_NOTIFY_SEARCHING_MSGID,         

    TAPI_NETWORK_NOTIFY_REGISTERING_MSGID,       

    TAPI_NETWORK_NOTIFY_UNAVAILABLE_MSGID,       

    TAPI_NETWORK_NOTIFY_BUSY_MSGID,              

    TAPI_NETWORK_NOTIFY_REGISTERED_MSGID,        

    TAPI_NETWORK_NOTIFY_EMERGENCY_CALL_ONLY_MSGID,

    TAPI_NETWORK_NOTIFY_DEREGISTER_MSGID,        

    TAPI_NETWORK_NOTIFY_SELECT_SERVICE_MSGID,    

    TAPI_NETWORK_NOTIFY_AVAILABLE_NETWORKS_MSGID,

    TAPI_NETWORK_NOTIFY_CURRENT_TIME_MSGID,      

    TAPI_NETWORK_NOTIFY_BAD_SIM_MSGID,           

    TAPI_NETWORK_NOTIFY_HOME_ZONE_INFOMSGID,     

    TAPI_NETWORK_NOTIFY_PLAY_SERVICE_TONE_MSGID, 

    TAPI_NETWORK_NOTIFY_REG_STATUS_MSGID,        

    TAPI_NETWORK_NOTIFY_HIDE_OPERATOR_LOGO_MSGID,
    TAPI_NETWORK_NOTIFY_REG_INFO_UPDATE_MSGID,   

    TAPI_NETWORK_NOTIFY_MA_TYPE_MSGID,            

    TAPI_NETWORK_NOTIFY_RF_MODE_CHANGE_MSGID,       

    TAPI_NETWORK_NOTIFY_HSDPA_AVAILABILITY_MSGID,

    TAPI_APP_ASYNC_NETWORK_MSG_GRPID_END         = TAPI_NETWORK_NOTIFY_HSDPA_AVAILABILITY_MSGID,

    TAPI_GPRS_NOTIFY_CONNECT_MSGID               = TAPI_APP_ASYNC_GPRS_MSG_GRPID + 1,   

    TAPI_GPRS_NOTIFY_RELEASE_MSGID,              

    TAPI_GPRS_NOTIFY_NOCARRIER_MSGID,            

    TAPI_GPRS_NOTIFY_ATTACH_STATUS_MSGID,        

    TAPI_GPRS_NOTIFY_SERVICE_STATUS_MSGID,       

    TAPI_GPRS_NOTIFY_AUTO_ATTACH_FEATURE_MSGID,  

    TAPI_GPRS_NOTIFY_FEATURE_STATUS_MSGID,       

    TAPI_GPRS_NOTIFY_MENU_STATUS_MSGID,          

    TAPI_GPRS_NOTIFY_ERROR_MSGID,                

    TAPI_GPRS_NOTIFY_TIMEOUT_MSGID,              

    TAPI_EGPRS_NOTIFY_SERVICE_STATUS_MSGID,      

    TAPI_EGPRS_NOTIFY_TRANSMITTING_OVER_EGPRS_MSGID,

    TAPI_GPRS_NOTIFY_SERVICE_STATE_CHANGE_MSGID, 

    TAPI_GPRS_NOTIFY_NETWORK_REG_STATUS_MSGID,   

    TAPI_GPRS_NOTIFY_ATTACH_DETACH_RESULT_MSGID,   

    TAPI_GPRS_NOTIFY_ALWAYS_ON_PLMN_TYPE_MSGID,  

    TAPI_GPRS_NOTIFY_DATA_TRANSFER_MSGID,        

    TAPI_APP_ASYNC_GPRS_MSG_GRPID_END            = TAPI_GPRS_NOTIFY_DATA_TRANSFER_MSGID,

    TAPI_STK_ASYNC_MIN_MSGID                     = TAPI_APP_ASYNC_STK_MSG_GRPID + 1, 
    TAPI_STK_NOTIFY_INIT_ROOT_MENU_MSGID         = TAPI_STK_ASYNC_MIN_MSGID,         

    TAPI_STK_NOTIFY_DISPLAY_TEXT_MSGID,          

    TAPI_STK_NOTIFY_GET_INKEY_MSGID,             

    TAPI_STK_NOTIFY_GET_INPUT_MSGID,             

    TAPI_STK_NOTIFY_PLAY_TONE_MSGID,             

    TAPI_STK_NOTIFY_SETUP_MENU_MSGID,            

    TAPI_STK_NOTIFY_SELECT_ITEM_MSGID,           

    TAPI_STK_NOTIFY_SEND_SMS_MSGID,              

    TAPI_STK_NOTIFY_SEND_SS_MSGID,               

    TAPI_STK_NOTIFY_SEND_USSD_MSGID,             

    TAPI_STK_NOTIFY_SETUP_CALL_MSGID,            

    TAPI_STK_NOTIFY_REFRESH_MSGID,               

    TAPI_STK_NOTIFY_REFRESH_END_MSGID,           

    TAPI_STK_NOTIFY_LAUNCH_BROWSER_MSGID,        

    TAPI_STK_NOTIFY_LANGUAGE_MSGID,              

    TAPI_STK_NOTIFY_IDLE_MODE_TEXT_MSGID,        

    TAPI_STK_NOTIFY_SEND_DTMF_START_MSGID,       

    TAPI_STK_NOTIFY_SEND_DTMF_STOP_MSGID,        

    TAPI_STK_NOTIFY_RUNAT_START_ALPHA_MSGID,     

    TAPI_STK_NOTIFY_RUNAT_STOP_ALPHA_MSGID,         

    TAPI_STK_NOTIFY_USER_ACTIVITY_MSGID,         

    TAPI_STK_NOTIFY_IDLE_SCREEN_AVAILBLE_MSGID,  

    TAPI_STK_NOTIFY_BROWSER_TERMINATION_MSGID,   

    TAPI_STK_NOTIFY_CLASS_E_ALPHAID_MSGID,       

    TAPI_STK_NOTIFY_CLASS_E_CREATE_SET_MSGID,    

    TAPI_STK_NOTIFY_CLASS_E_ACTIVATE_PROXY_MSGID,

    TAPI_STK_NOTIFY_CLASS_E_DESTROY_PROXY_MSGID, 

    TAPI_STK_NOTIFY_CLASS_E_SEND_DATA_MSGID,     

    TAPI_STK_ENVELOPE_DATA_AVAILABLE_MSGID,      

    TAPI_STK_ENVELOPE_CHANNEL_STATUS_MSGID,      

    TAPI_STK_BUFFER_FLOW_CONTROL_STATE,          

    TAPI_STK_NOTIFY_MENU_SELECTION_MSGID,        

    TAPI_STK_NOTIFY_MENU_SELECTION_END_MSGID,    

    TAPI_STK_ASYNC_MAX_MSGID                     = TAPI_STK_NOTIFY_MENU_SELECTION_END_MSGID,

    TAPI_APP_ASYNC_STK_MSG_GRPID_END             = TAPI_STK_ASYNC_MAX_MSGID,

    TAPI_CSD_NOTIFY_RING_MSGID                   = TAPI_APP_ASYNC_CSD_MSG_GRPID + 1, 

    TAPI_CSD_NOTIFY_CONNECT_MSGID,               

    TAPI_CSD_NOTIFY_BUSY_MSGID,                  

    TAPI_CSD_NOTIFY_NO_DIAL_TONE_MSGID,          

    TAPI_CSD_NOTIFY_NO_ANSWER_MSGID,             

    TAPI_CSD_NOTIFY_NO_CARRIER_MSGID,            

    TAPI_CSD_NOTIFY_OK_MSGID,                    

    TAPI_CSD_NOTIFY_ERROR_MSGID,                 

    TAPI_CSD_NOTIFY_TIMEOUT_MSGID,               

    TAPI_CSD_NOTIFY_OTHERAPP_DIALING_MSGID,      

    TAPI_CSD_NOTIFY_OTHERAPP_CONNECTING_MSGID,   

    TAPI_CSD_NOTIFY_NETWORK_ERROR_MSGID,             

    TAPI_APP_ASYNC_CSD_MSG_GRPID_END             = TAPI_CSD_NOTIFY_NETWORK_ERROR_MSGID,

    TAPI_CALLSET_NOTIFY_DIVERT_ICON_STATUS_MSGID = TAPI_APP_ASYNC_CALLSET_MSG_GRPID + 1,  

    TAPI_APP_ASYNC_CALLSET_MSG_GRPID_END         = TAPI_CALLSET_NOTIFY_DIVERT_ICON_STATUS_MSGID,

    TAPI_CB_NOTIFY_INFO_MSGID                    = TAPI_APP_ASYNC_CB_MSG_GRPID + 1,      

    TAPI_CB_QV_NEW_CELL_IND_MSGID,               

    TAPI_APP_ASYNC_CB_MSG_GRPID_END              = TAPI_CB_QV_NEW_CELL_IND_MSGID, 

    TAPI_USSD_NOTIFY_INFO_MSGID                  = TAPI_APP_ASYNC_USSD_MSG_GRPID + 1,    

    TAPI_USSD_NOTIFY_SS_MSGID,                  

    TAPI_USSD_NOTIFY_STK_RESULT_MSGID,          

    TAPI_USSD_NOTIFY_CALL_CONTROL_MSGID,        

    TAPI_USSD_NOTIFY_PASSWORD_NEEDED_MSGID,     

    TAPI_USSD_NOTIFY_OTHERAPP_RESPONDED_MSGID,  

    TAPI_APP_ASYNC_USSD_MSG_GRPID_END            = TAPI_USSD_NOTIFY_OTHERAPP_RESPONDED_MSGID,

    TAPI_FAX_NOTIFY_RING_MSGID                   = TAPI_APP_ASYNC_FAX_MSG_GRPID + 1,         

    TAPI_FAX_NOTIFY_CONNECT_MSGID,               

    TAPI_FAX_NOTIFY_BUSY_MSGID,                  

    TAPI_FAX_NOTIFY_NODIALTONE_MSGID,            

    TAPI_FAX_NOTIFY_NOANSWER_MSGID,              

    TAPI_FAX_NOTIFY_NOCARRIER_MSGID,             

    TAPI_FAX_NOTIFY_OK_MSGID,                    

    TAPI_FAX_NOTIFY_ERROR_MSGID,                 

    TAPI_FAX_NOTIFY_TIMEOUT_MSGID,               

    TAPI_FAX_NOTIFY_OTHERAPP_DIALING_MSGID,      

    TAPI_FAX_NOTIFY_OTHERAPP_CONNECTING_MSGID,   

    TAPI_APP_ASYNC_FAX_MSG_GRPID_END             = TAPI_FAX_NOTIFY_OTHERAPP_CONNECTING_MSGID,

    TAPI_EFEM_NOTIFY_CELL_CHANGE_MSGID           = TAPI_APP_ASYNC_EFEM_MSG_GRPID + 1,    
    TAPI_EFEM_NOTIFY_DATA_MSGID,                 

    TAPI_EFEM_NOTIFY_CELL_STICKER_RESULT_MSGID,  
    TAPI_EFEM_NOTIFY_DATA_RESPONSE_MSGID,        

    TAPI_EFEM_NOTIFY_UMA_STATE_CHANGE_MSGID,     

    TAPI_APP_ASYNC_EFEM_MSG_GRPID_END            = TAPI_EFEM_NOTIFY_UMA_STATE_CHANGE_MSGID,

    TAPI_BATTERY_NOTIFY_CHARGER_STATUS_MSGID     = TAPI_APP_ASYNC_MISC_MSG_GRPID + 1,    
    TAPI_BATTERY_NOTIFY_STATUS_MSGID,            

    TAPI_BATTERY_NOTIFY_VALUE_MSGID,             
    TAPI_BATTERY_NOTIFY_LOW_LEVEL_MSGID,         
    TAPI_BATTERY_NOTIFY_EXHAUSTED_MSGID,         
    TAPI_NOTIFY_EIHF_STATUS_MSGID,
    TAPI_NOTIFY_SMART_SPD_STATUS_MSGID,
    TAPI_SYNC_NOTIFY_STATUS_MSGID,               

    TAPI_POWER_NOTIFY_ON_MODE_MSGID,            

    TAPI_POWER_NOTIFY_DOWN_MSGID,               
    TAPI_SYNC_NOTIFY_WELCOME_MESSAGE_MSGID,     

    TAPI_FIXDIALING_NOTIFY_AVAIL_MSGID,         

    TAPI_SDN_NOTIFY_AVAIL_MSGID,                

    TAPI_APP_ASYNC_MISC_MSG_GRPID_END           = TAPI_SDN_NOTIFY_AVAIL_MSGID,

    TAPI_UMAN_NOTIFY_NETWORK_STATUS_MSGID       = TAPI_APP_ASYNC_UMAN_MSG_GRPID + 1,  

    TAPI_UMAN_NOTIFY_DIAG_STRING_MSGID,         

    TAPI_UMAN_NOTIFY_REG_ERROR_MSGID,           

    TAPI_UMAN_NOTIFY_GAN_SERVICE_ZONE_PARAMS_MSGID, 

    TAPI_APP_ASYNC_UMAN_MSG_GRPID_END           = TAPI_UMAN_NOTIFY_GAN_SERVICE_ZONE_PARAMS_MSGID,

    TAPI_CALL_NOTIFY_RINGBACK_MSGID             = TAPI_APP_ASYNC_CALL_MSG_GRPID + 1,    

    TAPI_CALL_NOTIFY_CREDIT_AVAILABLE_MSGID,  

    TAPI_CALL_NOTIFY_MODE_CHANGE_MSGID,       
    TAPI_CALL_NOTIFY_CONNECT_MSGID,           
    TAPI_CALL_NOTIFY_OTHERAPP_CALLING_MSGID,  

    TAPI_CALL_NOTIFY_INCOMING_MSGID,          
    TAPI_CALL_NOTIFY_DISCONNECTED_MSGID,      
    TAPI_CALL_NOTIFY_OPTIONS_MODIFIED_MSGID,  

    TAPI_APP_ASYNC_CALL_MSG_GRPID_END           = TAPI_CALL_NOTIFY_OPTIONS_MODIFIED_MSGID,

    TAPI_STK_NOTIFY_RUNAT_SOFTMODEM_READY_MSGID  =  TAPI_APP_ASYNC_STK_MULTI_REG_MSG_GRPID + 1,   

    TAPI_STK_NOTIFY_RUNAT_RESPONSE_AVAILABLE_MSGID, 

    TAPI_STK_NOTIFY_RUNAT_COMMAND_MSGID,        
    TAPI_STK_NOTIFY_RUANT_STOP_SOFTMODEM_MSGID, 

    TAPI_APP_ASYNC_STK_MULTI_REG_MSG_GRPID_END = TAPI_STK_NOTIFY_RUANT_STOP_SOFTMODEM_MSGID,

    TAPI_KODIAK_SMS_NOTIFY_RECV_NEW_SM_MSGID   = TAPI_APP_ASYNC_KODIAK_MSG_GRPID + 1, 

    TAPI_APP_ASYNC_KODIAK_MSG_GRPID_END        = TAPI_KODIAK_SMS_NOTIFY_RECV_NEW_SM_MSGID

};

typedef UINT16  TAPI_APP_MSGID_T;

#ifdef __cplusplus
}

#endif
#endif 
